export const HOME = '/'
export const ACCOUNT = '/account'
export const TASKS = '/tasks'
export const USERS = '/users'
export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const FORGOT = '/forgot'
